[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "1.1.2"
solana_version = "3.1.10"

[programs.localnet]
solgift_escrow = "A5cFtpUVnBncPqaBpUjHUtb9brk3qoPZSUjRdD3DTht2"

[programs.devnet]
solgift_escrow = "A5cFtpUVnBncPqaBpUjHUtb9brk3qoPZSUjRdD3DTht2"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
