[features]
seeds = false
skip-lint = false

[programs.localnet]
solgift_escrow = "A5cFtpUVnBncPqaBpUjHUtb9brk3qoPZSUjRdD3DTht2"

[programs.devnet]
solgift_escrow = "A5cFtpUVnBncPqaBpUjHUtb9brk3qoPZSUjRdD3DTht2"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
